# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HikeSimulation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~>4.7.3'
    #pod 'SwiftyJSON', '~> 4.0'
    pod 'AlamofireObjectMapper', '~>5.1.0'
    pod 'Kingfisher'
    pod 'ObjectMapper', '~> 3.4'
  # Pods for HikeSimulation

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
